using ErkS.Platform.Contracts;

namespace ErkS.Platform.Core;

/// <summary>
/// Studio-owned composition for a building architecture concept album. Fixed
/// information pages are generated by Studio; source slots are filled by
/// Revit, AutoCAD, CityGen or another registered producer.
/// </summary>
public static class BuildingArchitectureConceptAlbumTemplate
{
    public const string TemplateId = "building-architecture-concept-v1";

    public static AlbumDefinition CreateDefinition(string title)
    {
        var definition = new AlbumDefinition
        {
            Title = title,
            TemplateId = TemplateId,
            IncludeCover = false,
            IncludeTableOfContents = false,
            Composition = CreateComposition(),
        };
        EnsureSections(definition);
        return definition;
    }

    public static bool Ensure(StudioAlbumDocument album)
    {
        if (!string.Equals(
                album.PackageType,
                ProjectWorkspace.BuildingArchitectureConcept,
                StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        return Ensure(album.Definition);
    }

    public static bool Ensure(AlbumDefinition definition)
    {
        if (!string.IsNullOrWhiteSpace(definition.TemplateId) &&
            !string.Equals(definition.TemplateId, TemplateId, StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var changed = false;
        if (definition.Composition.Count == 0)
        {
            definition.TemplateId = TemplateId;
            definition.Composition = CreateComposition();
            definition.IncludeCover = false;
            definition.IncludeTableOfContents = false;
            changed = true;
        }
        else if (string.IsNullOrWhiteSpace(definition.TemplateId))
        {
            definition.TemplateId = TemplateId;
            changed = true;
        }

        AlbumCompositionItem? siteContext = definition.Composition.FirstOrDefault(item =>
            item.Id.Equals("site-context", StringComparison.OrdinalIgnoreCase));
        if (siteContext is null)
        {
            definition.Composition.Add(Generated(
                "site-context",
                3,
                "03",
                "БАЙРШЛЫН СХЕМ / ОРЧНЫ ТОЙМ",
                "Ерөнхий төлөвлөгөө",
                AlbumGeneratedPageKind.SiteContext));
            definition.Composition = definition.Composition
                .OrderBy(item => item.Order)
                .ToList();
            changed = true;
        }
        else if (
            (siteContext.Kind != AlbumCompositionKind.Generated ||
             siteContext.GeneratedPageKind != AlbumGeneratedPageKind.SiteContext ||
             !siteContext.Title.Equals("БАЙРШЛЫН СХЕМ / ОРЧНЫ ТОЙМ", StringComparison.Ordinal)))
        {
            siteContext.Kind = AlbumCompositionKind.Generated;
            siteContext.GeneratedPageKind = AlbumGeneratedPageKind.SiteContext;
            siteContext.Title = "БАЙРШЛЫН СХЕМ / ОРЧНЫ ТОЙМ";
            siteContext.Required = true;
            siteContext.AllowMultiple = false;
            siteContext.MatchContentKinds = [];
            siteContext.MatchNameTerms = [];
            changed = true;
        }

        changed |= EnsureSections(definition);
        return changed;
    }

    public static AlbumCompositionItem? FindSourceSlot(
        AlbumDefinition definition,
        SheetPackageEntry entry)
    {
        var sourceSlots = definition.Composition
            .Where(item => item.Kind == AlbumCompositionKind.SourceSlot)
            .OrderBy(item => item.Order)
            .ToList();

        var contentHints = new[] { entry.ContentKind, entry.Discipline }
            .Where(value => !string.IsNullOrWhiteSpace(value));
        var bySourceMetadata = sourceSlots.FirstOrDefault(item => item.MatchContentKinds.Any(expected =>
            contentHints.Any(actual => EqualsNormalized(actual, expected))));
        if (bySourceMetadata is not null)
        {
            return bySourceMetadata;
        }

        return sourceSlots.FirstOrDefault(item =>
            item.MatchNameTerms.Any(term => Contains(entry.Name, term)));
    }

    public static AlbumCompositionItem? FindSlot(AlbumDefinition definition, string? slotId) =>
        string.IsNullOrWhiteSpace(slotId)
            ? null
            : definition.Composition.FirstOrDefault(item =>
                string.Equals(item.Id, slotId, StringComparison.OrdinalIgnoreCase));

    public static Guid? ResolveSectionId(AlbumDefinition definition, AlbumCompositionItem? slot)
    {
        if (slot is null || string.IsNullOrWhiteSpace(slot.SectionTitle))
        {
            return null;
        }

        var section = definition.Sections.FirstOrDefault(item =>
            string.Equals(item.Title, slot.SectionTitle, StringComparison.OrdinalIgnoreCase));
        return section?.Id;
    }

    public static IReadOnlyList<AlbumPageDefinition> OrderSourcePages(
        AlbumDefinition definition,
        IEnumerable<AlbumPageDefinition> pages)
    {
        var order = definition.Composition.ToDictionary(
            item => item.Id,
            item => item.Order,
            StringComparer.OrdinalIgnoreCase);
        return pages
            .Select((page, index) => new { Page = page, Index = index })
            .OrderBy(item => order.TryGetValue(item.Page.TemplateSlotId, out var value) ? value : int.MaxValue)
            .ThenBy(item => item.Index)
            .Select(item => item.Page)
            .ToList();
    }

    private static List<AlbumCompositionItem> CreateComposition() =>
    [
        Generated("cover", 0, "00", "НҮҮР ХУУДАС", "Нүүр хуудас", AlbumGeneratedPageKind.Cover),
        Generated("design-organization", 1, "01", "ЗУРАГ ТӨСӨЛ БОЛОВСРУУЛСАН БАЙГУУЛЛАГА", "Ерөнхий хэсэг", AlbumGeneratedPageKind.DesignOrganization),
        Generated("planning-task", 2, "02", "БАТЛАГДСАН АРХИТЕКТУР ТӨЛӨВЛӨЛТИЙН ДААЛГАВАР", "Ерөнхий хэсэг", AlbumGeneratedPageKind.PlanningTask),
        Generated("site-context", 3, "03", "БАЙРШЛЫН СХЕМ / ОРЧНЫ ТОЙМ", "Ерөнхий төлөвлөгөө", AlbumGeneratedPageKind.SiteContext),
        Source("planning-proposal", 4, "04", "ТӨЛӨВЛӨЛТИЙН САНАА", "Ерөнхий төлөвлөгөө", false, [], ["ТӨЛӨВЛӨЛТИЙН САНАА"]),
        Source("traffic-scheme", 5, "05", "ХӨДӨЛГӨӨНИЙ СХЕМ", "Ерөнхий төлөвлөгөө", false, [], ["ХӨДӨЛГӨӨНИЙ СХЕМ"]),
        Source("landscaping", 6, "06", "НОГООН БАЙГУУЛАМЖ", "Ерөнхий төлөвлөгөө", false, [], ["НОГООН БАЙГУУЛАМЖ"]),
        Source("solar-study", 7, "07", "НАРНЫ ЭЭВЭРЛЭЛТ", "Ерөнхий төлөвлөгөө", false, [], ["НАРНЫ ЭЭВЭРЛЭЛТ", "НАРНЫ ТУСГАЛ"]),
        Source("master-plan", 8, "08", "ЕРӨНХИЙ ТӨЛӨВЛӨГӨӨ", "Ерөнхий төлөвлөгөө", false, [], ["ЕРӨНХИЙ ТӨЛӨВЛӨГӨӨ"]),
        Source("floor-plans", 9, "09+", "ДАВХРЫН БАЙГУУЛАЛТ", "Давхрын байгуулалт", true, ["Давхрын байгуулалт", "Байгуулалт"], ["ДАВХРЫН БАЙГУУЛАЛТ"]),
        Source("sections", 10, "10+", "ОГТЛОЛ", "Огтлол", true, ["Огтлол"], ["ОГТЛОЛ"]),
        Source("elevations", 11, "11+", "НҮҮР ТАЛ", "Нүүр тал", true, ["Нүүр тал"], ["НҮҮР ТАЛ"]),
        Source("visualizations", 12, "12+", "ХАРАГДАХ БАЙДАЛ", "Харагдах байдал", true, ["Харагдах байдал"], ["ХАРАГДАХ БАЙДАЛ"]),
    ];

    private static AlbumCompositionItem Generated(
        string id,
        int order,
        string number,
        string title,
        string section,
        AlbumGeneratedPageKind pageKind) => new()
        {
            Id = id,
            Order = order,
            Number = number,
            Title = title,
            SectionTitle = section,
            Kind = AlbumCompositionKind.Generated,
            GeneratedPageKind = pageKind,
        };

    private static AlbumCompositionItem Source(
        string id,
        int order,
        string number,
        string title,
        string section,
        bool allowMultiple,
        List<string> contentKinds,
        List<string> nameTerms) => new()
        {
            Id = id,
            Order = order,
            Number = number,
            Title = title,
            SectionTitle = section,
            Kind = AlbumCompositionKind.SourceSlot,
            AllowMultiple = allowMultiple,
            MatchContentKinds = contentKinds,
            MatchNameTerms = nameTerms,
        };

    private static bool EnsureSections(AlbumDefinition definition)
    {
        var changed = false;
        foreach (var title in definition.Composition
                     .Select(item => item.SectionTitle)
                     .Where(title => !string.IsNullOrWhiteSpace(title))
                     .Distinct(StringComparer.OrdinalIgnoreCase))
        {
            if (definition.Sections.Any(section =>
                    string.Equals(section.Title, title, StringComparison.OrdinalIgnoreCase)))
            {
                continue;
            }

            definition.Sections.Add(new AlbumSection { Title = title });
            changed = true;
        }
        return changed;
    }

    private static bool Contains(string? value, string expected) =>
        !string.IsNullOrWhiteSpace(value) &&
        value.Contains(expected, StringComparison.OrdinalIgnoreCase);

    private static bool EqualsNormalized(string? left, string? right) =>
        string.Equals(left?.Trim(), right?.Trim(), StringComparison.OrdinalIgnoreCase);
}
