using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using ErkS.Studio;

namespace ErkS.Studio.App.Tests;

/// <summary>
/// Renders the published refusal catalogue.
///
/// One copy, used by the test that compares the published file and by anything
/// that regenerates it. An emitter with its own copy of this shape is how the
/// file and the check that guards it come to describe different documents -
/// which is the failure mode this whole contract exists to prevent, arrived at
/// from the inside.
/// </summary>
internal static class SsoContractRenderer
{
    private static readonly JsonSerializerOptions Options =
        new(JsonSerializerDefaults.Web)
        {
            WriteIndented = true,
            Converters = { new JsonStringEnumConverter() },
        };

    /// <summary>
    /// What each check CANNOT establish, for the codes where the name is wider
    /// than the evidence.
    ///
    /// 🔴 PFA'S IDEA, TAKEN. Renaming sso_device_mismatch fixed today's wrong
    /// name; this stops the next one. A reader meeting a code reads its name as
    /// the claim, and the day somebody widens a check - or narrows it - the
    /// sentence beside it is what tells them the name no longer fits.
    /// </summary>
    private static readonly Dictionary<string, string> CannotEstablish = new(StringComparer.Ordinal)
    {
        ["sso_signature_invalid"] =
            "Төхөөрөмжийн зөрөлтийг БАТЛАХГҮЙ: үг үсгээр хуулсан бичлэг энэ шалгалтыг " +
            "давна. Мөн формат буруу барьсан уншигч дээр ч гарна — тиймээс хэрэглэгчийг " +
            "буруутгаж болохгүй. Төхөөрөмжийн зөрөлтийг зөвхөн сервер барина " +
            "(sso_device_mismatch).",
        ["sso_handoff_token_missing"] =
            "Лиценз байхгүй гэсэн үг БИШ: таних тэмдэг бий, нотолгоо нь хараахан " +
            "олгогдоогүй байна.",
        ["sso_seat_token_absent"] =
            "Суудал хүчингүй гэсэн үг БИШ: суудал хэвээр, зөвхөн нотолгоо нь " +
            "хараахан олгогдоогүй. Хүнд «нэвтэрнэ үү» гэж хэлэх нь буруу зүг — " +
            "хажууд нь аль хэдийн нэвтэрсэн байж болно.",
        ["sso_store_unavailable"] =
            "Бичлэг байхгүй гэсэн үг БИШ: санд хүрч чадаагүй тул юу байгааг мэдэхгүй.",
    };

    public static string Codes()
    {
        var codes = new JsonArray();
        foreach (StudioSsoRefusal refusal in StudioSsoRefusalCatalogue.All)
        {
            var entry = new JsonObject
            {
                ["code"] = refusal.Code,
                ["origin"] = refusal.Origin.ToString(),
                ["httpStatus"] = refusal.HttpStatus,
                ["checkOrder"] = refusal.CheckOrder,
                ["nextStep"] = refusal.NextStep.ToString(),
                ["messageMn"] = refusal.MessageMn,
            };
            if (CannotEstablish.TryGetValue(refusal.Code, out string? limit))
                entry["cannotEstablish"] = limit;
            codes.Add(entry);
        }

        var file = new JsonObject
        {
            ["_comment"] = new JsonArray
            {
                "GENERATED by SsoRefusalCatalogueTests. Do not edit by hand - every " +
                "hand-copy of this list has been wrong, because a new code arrives " +
                "silently and every line of the old copy stays true.",
                "",
                "Compare your reader's constants against this file. Names, order and " +
                "sentences all live here; the nearest other implementation is not a " +
                "reference.",
                "",
                "origin: Reader = decided from the resting record before any request. " +
                "Server = decided when the token is presented. Four codes are both, " +
                "deliberately: one situation gets one sentence whichever side noticed it.",
                "",
                "expiry: the WRITER puts the earlier of the record's own life and the " +
                "token's into expiresAtUtc. A reader checks that one field and nothing " +
                "else - there is no separate token expiry to read, and opening the " +
                "token to look would be parsing a proof that is deliberately opaque. " +
                "See invariants.recordExpiryIsCappedByTokenExpiry.",
                "",
                "checkOrder: the step a reader raises it at. Order is part of the " +
                "contract - each step makes the fields below it mean something.",
                "",
                "cannotEstablish: what the check does NOT prove. Present where the name " +
                "is wider than the evidence, so the next reader does not repeat the " +
                "mistake sso_device_mismatch made on this side.",
            },
            ["messageComposition"] = new JsonObject
            {
                ["rule"] = "append-only",
                ["_rule"] = new JsonArray
                {
                    "A product MAY append its own context to messageMn - which seat is " +
                    "asking for a PIN, which version was found, where the file was. It " +
                    "MUST NOT replace the sentence.",
                    "",
                    "Match by PREFIX, not by equality: a reader comparing whole strings " +
                    "would reject every message that carries context, which is the " +
                    "shape that makes people stop appending anything useful.",
                    "",
                    "PFA's rule, written here rather than told to three teams - a rule " +
                    "delivered as a message is a rule copied into three places, which is " +
                    "the drift this file exists to stop.",
                },
            },
            ["invariants"] = Invariants(),
            ["codes"] = codes,
        };
        return (file.ToJsonString(Options) + "\n").Replace("\r\n", "\n");
    }

    /// <summary>
    /// Facts about the record that a reader depends on and cannot check for
    /// itself.
    ///
    /// 🔴 MEASURED, NOT DECLARED. PFA reads the record's expiry and trusts that
    /// it is never longer than the token inside it - and the token is opaque to
    /// them, so they CANNOT verify it. If Studio quietly dropped the cap, PFA
    /// would break with nothing red anywhere.
    ///
    /// So the value published here is the OUTCOME of running the publisher, not
    /// a constant somebody keeps in step by hand. Remove the cap and this file
    /// changes; change the file by hand and the comparison test goes red. The
    /// side that can prove the invariant owns the proof; the side that depends
    /// on it declares the dependency.
    /// </summary>
    private static JsonObject Invariants()
    {
        var now = new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);
        StudioSsoIdentityRecord capped = StudioSsoIdentityPublisher.Build(
            new StudioSsoIdentityInputs(
                "invariant-probe@erk-s.mn",
                null,
                null,
                false,
                "SHA256:PROBE",
                "SHA256:PROBE-LEGACY",
                "probe-token",
                now.AddDays(2),
                StudioSsoHandoffScope.Person,
                now),
            previous: null);

        return new JsonObject
        {
            ["recordExpiryIsCappedByTokenExpiry"] = capped.ExpiresAtUtc == now.AddDays(2),
            ["_recordExpiryIsCappedByTokenExpiry"] =
                "Measured by building a record whose token expires before the record " +
                "otherwise would. True means expiresAtUtc is never later than the " +
                "token inside it, so a reader may treat the record's expiry as the " +
                "expiry of the proof it carries.",
        };
    }
}
