<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ErkS.Platform.Core\ErkS.Platform.Core.csproj" />
    <ProjectReference Include="..\ErkS.Platform.Contracts\ErkS.Platform.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ErkS.Platform.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\Erk-S Platform For Autocad\src\autocad\2026-dev\source\Fonts\isocpeu_mon_3.ttf"
             Link="Fonts\isocpeu_mon_3.ttf"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\..\..\Erk-S Platform For Autocad\src\autocad\2026-dev\source\Fonts\isocpeui_mon_3.ttf"
             Link="Fonts\isocpeui_mon_3.ttf"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
